### ISSUE TITLE
SkyOS 에서 처음 SkyOS.BAT 파일을 실행했을 때, SkyOS.IMA 파일을 찾을 수 없다고 하면?

### ISSUE THREAD

**Issue by melonicedlatte** [pdpdds/SkyOS#1]
BAT 파일을 열어보면 IMA 의 확장자가 ima 로 되어 있을 겁니다. 
BAT 파일의 ima를 IMA로 변경해주면 해결됩니다.

**Comment by pdpdds** [comment]
확장자는 상관없는데 이미지 파일을 인식하지 못했다는 뜻인지요?

**Comment by melllon00** [comment]
제가 파일을 다운받을 때에는 IMA 대문자로 나와있었고, BAT 파일 내부에는 ima 소문자로 되어 있었습니다. 파일의 확장자는 결국 ima로 똑같은데 같은데, 다른 컴퓨터는 모르겠지만 저 같은 경우에는 BAT파일을 실행하면 이미지 파일을 찾지 못하더군요. 혹시, 안되시는 분들을 위하여 참고하시라는 의미에서 적어 놓았습니다.

**Comment by pdpdds** [comment]
일단 제 컴퓨터에서는 문제가 없는 걸로 봐서 특정 OS에서 발생하는 문제인 걸로 보입니다. 문제점을 알려주셔서 감사드리며  다른 문제가 발생했을 때 알려주시면 바로 대응해 드리겠습니다.

**Comment by melllon00** [comment]
빠른 답변 감사합니다. 꼭, 꾸준히 개발해서 저만의 OS를 만들어 보고 싶네요 ㅎ

**Comment by pdpdds** [comment]
자신만의 OS를 제작하는데 SkyOS가 조금이나마 도움이 되었으면 좋겠군요 ^^

**Comment by Arkingco** [comment]
저도 같은문제가 생겨서 질문드립니다.
텍스트 파일로 열어서 .IMA 수정을하고 실행을 해보아도 
qemu-system-x86_64: Could not open 'SkyOS.IMA': ??????????? ???????????????????? 
이런 메시지가 나오네요 혹시나해서 qemu 구글드라이브에 있는 파일말고 업데이트 된 버전으로 
재설치를 진행해 보았는데 똑같은 문제가 있네요  혹시 방법좀 알수 있을까요

**Comment by Arkingco** [comment]
문제 해결 했습니다.

**Comment by khw8607** [comment]
동일 문제발생하여 확장자 명 변경하였는데 그대로네요.

C:\Program Files\qemu>REM Start qemu on windows.
qemu-system-x86_64: -localtime: warning: This option is deprecated, use '-rtc base=localtime' instead.
qemu-system-x86_64: -fda SkyOS.IMA: Could not open 'SkyOS.IMA': ?≪꽭?ㅺ? 嫄곕??섏뿀?듬땲??
계속하려면 아무 키나 누르십시오 . . .

**Comment by Arkingco** [comment]
![image](https://user-images.githubusercontent.com/28525747/53778815-6b789700-3f41-11e9-90d5-e4117e2224be.png)
고급 누르고

![d082cec9-0c99-4f5c-8a41-a2fcf2e838c2 png](https://user-images.githubusercontent.com/28525747/53778889-ada1d880-3f41-11e9-981a-b0a3f855fb24.jpg)
추가 누르고 

보안주체 선택하라는 메시지 누르고

아마 자기가 사용하고있는 계정의 이름을 적어주시면 될꺼에요

그리고 모든권한 부여하고 다시 실행해보니까 정상적으로 작동이 되더라고요

**Comment by khw8607** [comment]
똑같이해도 안되네요.. 이것때문에 진행을하기가 힘드네요 ㅜㅜ

**Comment by pdpdds** [comment]
지금 이 스레드에서 발생한 문제는 SkyOS 본연의 문제와 관계없는, 툴 실행의 문제입니다. 
- 다른 컴퓨터에서 테스트를 해본다
- D드라이브에서 테스트를 한다
- 관리자 권한으로 커맨드를 실행한다
- 실행 커맨드를 소문자로 통일한다
위에서 언급한 방법으로 문제를 파악해 보시기 바랍니다.

**Comment by cactus0707** [comment]
2020/11/02/ 구글 드라이브에 있는 IMA,BAT 파일로 hello world 보기 성공 / 비쥬얼스튜디오 2019 버전 Skyos 빌드 후 skyos.exe 인젝션 후 hello world 성공 / 깃 허브에 있는 권한 설정 변경으로 해결했습니다. 권한을 의심했던 이유는 BAT -> TXT 파일로  열고 저장시 권한이 없다는 메세지가 나왔고, 권한 설정 이미지 맨 마지막 부분에 제 PC 유저 이름 입력후 이름체크 후 실행시 정상 작동하였습니다. (생존신고 및 박주항님 화이팅)
