### ISSUE TITLE
git clone 은 문제 없는데 svn checkout 은 에러가 나네요.

### ISSUE THREAD

**Issue by sysroad** [pdpdds/SkyOS#2]
쓰신 책을 읽기 시작했는데
Ther server at 'https://github.com/pdpdds/SkyOS.git' does not support the HTTP/DAV protocol
라고 에러가 뜨네요~

**Comment by pdpdds** [comment]
언급해 주신 사항만 가지고는 원인을 알기 어려울 것 같습니다. 그리고 해당문제는 SkyOS 저장소만의 문제는 아닌 것 같습니다. 다른 저장소도 SVN 체크아웃시 똑같은 문제가 발생하는지 먼저 확인해야 할 것 같습니다.

**Comment by sysroad** [comment]
https://stackoverflow.com/questions/53129732/did-github-shut-down-its-support-for-subversion-clients

TortoiseSVN 최신버전 (1.11.0) 사용시에 문제가 발생하네요.
TortoiseSVN 이전 버전이나 SlikSVN 를 받아 사용하니 문제없습니다.
