### ISSUE TITLE
HelloWorld폴더 솔루션 빌드 시 CommonLib.lib 링크 에러

### ISSUE THREAD

**Issue by hsi409** [pdpdds/SkyOS#3]
안녕하세요.

Chapter - HelloWorld에 있는 솔루션 빌드시 에러가 발생합니다.

에러 내용은 아래와 같습니다.

================ 아 래 ================
Error	LNK1181	cannot open input file 'CommonLib.lib'	
====================================

프로젝트에서 CommonLib.lib를 사용하는데 HelloWorld 폴더 안에 없습니다.
CommonLib폴더에서 직접 빌드하여 넣어주니 정상적으로 빌드는 진행했는데
기본적으로는 에러가 발생해서 알려드립니다.

**Comment by pdpdds** [comment]
소스코드를 업데이트해서 다시 빌드해 보십시오. 예전에 이 문제를 알려주신 분이 있어서 소스코드가 업데이트 되었는데 이전 소스로 빌드하신 것 같습니다.

**Comment by hsi409** [comment]
방금 받은 소스 코드로 진행한 내용인데 다시 한번 해보긴 하겠습니다.

**Comment by pdpdds** [comment]
해당 이슈는 닫겠습니다.
