### ISSUE TITLE
책 사서 잘보고 있습니다. 질문이 있습니다.

### ISSUE THREAD

**Issue by hash1018** [pdpdds/SkyOS#7]
안녕하세요. 

책을 보면 3. 커널로딩 부분 

그래픽카드가 흑백일 경우 비디오 메모리의 주소는 0xb0000 , 컬러일경우 비디오 메모리의 주소는 0xb8000 등 적혀있습니다.

이러한 메모리 주소에 대한 레이아웃을 표현한 그림 이나 정보같은 건 어디서 찾을수 있을까요?
코드를 보니 16진수가 난무하니, 제가 이러한 메모리 레이아웃에 대해 이해할 필요성을 느낍니다.

http://www.read.seas.harvard.edu/~kohler/class/05f-osp/notes/lec03.html 이 사이트와 같이 
PC 물리 주소  그림에서 0xb8000에서 시작하는 주소가 표현되어있듯이 좀 이러한 구조를 보면서 제가 공부를 해야할거같습니다.

**Comment by pdpdds** [comment]
OSDev 사이트에서 필요하신 정보를 리서치하면 될 것 같네요.

**Comment by hash1018** [comment]
제가 원하는 정보를 찾았습니다. 감사합니다.
