### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by Juha3141** [pdpdds/SkyOS#8]
안녕하세요, 운영체제를 개발하고 있는 사람입니다. 책에서 보면 그래픽을 사용하려고 V806이라는 것을 사용하시는 것 같은데 V8086은 최신 PC에서는 잘 작동이 안된다는 단점이 있는 것 같습니다. 그래서 이 단점을 해결하기 위해서는 32비트 모드에서 16비트로 cr0의 값을 바꾸어서 바이오스 인터럽트를 사용해 그래픽 모드로 진입하고 다시 32비트 모드로 들어가는 방법이 있지 않을까요? 제가 이 방법을 같은 grub시스템에서 구현해봤는데 매우 잘 작동하더라고요. 그래서 V8086보다는 이 방법을 사용하는게 더 낫지 않을까요??
제가 참고한 자료입니다:
http://www.rohitab.com/discuss/topic/35103-switch-between-real-mode-and-protected-mode/

답변해주시면 정말 감사하겠습니다!

**Comment by JuhaCho** [comment]
물론, 저도 운영체제에 대해서 완전히 잘 아는것도 아니지만 그래도.. 궁금해서요

**Comment by pdpdds** [comment]
그래픽을 사용하기 위해 V86 모드를 사용하지 않습니다. V86 예제는 보호모드에서도 바이오스콜이 가능하다는 것을 보여주기 위한 샘플입니다. SkyOS는 GRUB을 통해 그래픽 모드로 진입합니다.

**Comment by JuhaCho** [comment]
감사합니다!
